### ISSUE TITLE
Temporarily failed to flush the buffer. NoMethodError

### ISSUE THREAD

**Issue by tbenade** [ryotarai/fluent-plugin-cloudwatch-logs#31]
Hi, looking for some guidance on what may be causing this error as soon as I post data to fluentd. I dont believe my config is anything other than trivial. Wondering if it could be related to my data. Are there any expectations on the shape of the data?

The configuration

```
<store>
      type cloudwatch_logs
      log_group_name fluentd_test
      use_tag_as_stream true
      auto_create_stream true
      region ap-southeast-2
</store>
```

016-01-06 02:37:50 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-06 02:37:51 +0000 error_class="NoMethodError" error="undefined method `[]=' for nil:NilClass" plugin_id="object:3fdd1113c044"
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:156:in`create_log_stream'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:66:in `block in write'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in`<<'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in `each'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in`each'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in `write'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:345:in`write_chunk'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:324:in `pop'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:321:in`try_flush'
  2016-01-06 02:37:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:140:in `run'
2016-01-06 02:37:51 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-06 02:37:53 +0000 error_class="NoMethodError" error="undefined method`[]' for nil:NilClass" plugin_id="object:3fdd1113c044"
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:101:in `next_sequence_token'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:137:in`put_events'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:127:in `put_events_by_chunk'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:95:in`block in write'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in `<<'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in`each'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in `each'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.1.2/lib/fluent/plugin/out_cloudwatch_logs.rb:51:in`write'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:345:in `write_chunk'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:324:in`pop'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:321:in `try_flush'
  2016-01-06 02:37:51 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:140:in`run'
2016-01-06 02:37:53 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-06 02:37:56 +0000 error_class="NoMethodError" error="undefined method `[]' for nil:NilClass" plugin_id="object:3fdd1113c044"
  2016-01-06 02:37:53 +0000 [warn]: suppressed same stacktrace
2016-01-06 02:37:57 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-06 02:38:04 +0000 error_class="NoMethodError" error="undefined method`[]' for nil:NilClass" plugin_id="object:3fdd1113c044"
  2016-01-06 02:37:57 +0000 [warn]: suppressed same stacktrace
2016-01-06 02:38:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-06 02:38:19 +0000 error_class="NoMethodError" error="undefined method `[]' for nil:NilClass" plugin_id="object:3fdd1113c044"

**Comment by ryotarai** [comment]
If you still have a problem, please send a pull request
