### ISSUE TITLE
Improve batching to keep request payload bellow the 32kb AWS api limit

### ISSUE THREAD

**Issue by nicktgr15** [ryotarai/fluent-plugin-cloudwatch-logs#6]
Hello,

When the combined size of log messages in the events variable is more than 32kB I get the following message:

```
2014-08-20 15:51:56 +0100 [warn]: temporarily failed to flush the buffer. next_retry=2014-08-20 15:51:47 +0100 error_class="MultiJson::ParseError" error="Yajl::ParseError" instance=20560000
```

I tried to limit the chunk size to 25kB (buffer_chunk_limit 25k)  but I still had issues as you can see bellow:

```
2014-08-20 15:51:12 +0100 [warn]: Size of the emitted data exceeds buffer_chunk_limit.
2014-08-20 15:51:12 +0100 [warn]: This may occur problems in the output plugins ``at this server.``
2014-08-20 15:51:12 +0100 [warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
2014-08-20 15:51:12 +0100 [warn]: in the forward output ``at the log forwarding server.``
2014-08-20 15:51:18 +0100 [warn]: temporarily failed to flush the buffer. next_retry=2014-08-20 15:51:18 +0100 error_class="MultiJson::ParseError" error="Yajl::ParseError" instance=20560000
```

I think that something similar with what amazon is doing for their agent should be done in order to address batching. The "How are log events batched?" section in their [docs](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/AgentReference.html) would be useful as a reference.

Thanks,
Nick

**Comment by chiefy** [comment]
Having a similar problem right now:
```
"log":"2015-09-11 16:06:58 +0000 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-09-11 16:06:03 +0000 error_class=\"Aws::CloudWatchLogs::Errors::ThrottlingException\" error=\"Rate exceeded\" plugin_id=\"object:3fc9e660a9c4\"\n","stream":"stdout","time":"2015-09-11T16:06:58.932202533Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.48/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'\n","stream":"stdout","time":"2015-09-11T16:06:58.93226979Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.48/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'\n","stream":"stdout","time":"2015-09-11T16:06:58.932293814Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.48/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'\n","stream":"stdout","time":"2015-09-11T16:06:58.932320424Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.48/lib/seahorse/client/plugins/response_target.rb:18:in `call'\n","stream":"stdout","time":"2015-09-11T16:06:58.932336741Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.48/lib/seahorse/client/request.rb:70:in `send_request'\n","stream":"stdout","time":"2015-09-11T16:06:58.932349163Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.48/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'\n","stream":"stdout","time":"2015-09-11T16:06:58.932361492Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:127:in `put_events'\n","stream":"stdout","time":"2015-09-11T16:06:58.932386207Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:106:in `put_events_by_chunk'\n","stream":"stdout","time":"2015-09-11T16:06:58.932397707Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:86:in `block in write'\n","stream":"stdout","time":"2015-09-11T16:06:58.932410201Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `\u003c\u003c'\n","stream":"stdout","time":"2015-09-11T16:06:58.932421958Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `each'\n","stream":"stdout","time":"2015-09-11T16:06:58.932433416Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `each'\n","stream":"stdout","time":"2015-09-11T16:06:58.932444973Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `write'\n","stream":"stdout","time":"2015-09-11T16:06:58.932455572Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:325:in `write_chunk'\n","stream":"stdout","time":"2015-09-11T16:06:58.93246493Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:304:in `pop'\n","stream":"stdout","time":"2015-09-11T16:06:58.932474157Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/output.rb:321:in `try_flush'\n","stream":"stdout","time":"2015-09-11T16:06:58.932484016Z"}
{"log":"  2015-09-11 16:06:58 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/output.rb:140:in `run'\n","stream":"stdout","time":"2015-09-11T16:06:58.93249417Z"}
```

**Comment by adamchainz** [comment]
The limits are higher than 32KiB (now) - see http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/cloudwatch_limits.html .

> * The maximum event size is 256KB.
> * The maximum batch size is 1MB.

The plugin should still work with those though. :+1:

**Comment by ryotarai** [comment]
If you still have a problem, please send a pull request
