### ISSUE TITLE
Potential issue related to AWS SDK 3.2

### ISSUE THREAD

**Issue by orasik** [ryotarai/fluent-plugin-cloudwatch-logs#77]
Hi,
I have updated config today to make a new docker build and I got the error:

```
2017-09-05 14:47:19 +0000 [error]: unexpected error error_class=NameError error=#<NameError: uninitialized constant Aws::CloudWatchLogs>
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.0/lib/fluent/plugin/out_cloudwatch_logs.rb:69:in `start'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:71:in `block in start'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:70:in `each'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:70:in `start'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:108:in `start'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:237:in `start'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:187:in `run'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:570:in `run_engine'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:162:in `block in start'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:366:in `main_process'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:339:in `block in supervise'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `fork'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `supervise'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:156:in `start'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-09-05 14:47:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/bin/fluentd:5:in `<top (required)>'
  2017-09-05 14:47:19 +0000 [error]: /usr/bin/fluentd:22:in `load'
  2017-09-05 14:47:19 +0000 [error]: /usr/bin/fluentd:22:in `<main>'
```

comparing my current build with old builds (which are working perfectly) I noticed that during installation it did install `aws-sdk-core-3.2.0` while old builds install `aws-sdk-core-2.10.31`

Could it be the issue?

**Comment by sampointer** [comment]
https://aws.amazon.com/blogs/developer/aws-sdk-for-ruby-modularization-version-3-2/

v3 requires gems for each service to be explicitly required.

**Comment by orasik** [comment]
that means we need to strict aws-ask in gemspec file to `~>2.0`? I have forked the repo and trying this at the moment.

is there a better solution? sorry I'm not a ruby dev.

**Comment by sampointer** [comment]
Yes.

For example: https://github.com/sampointer/fluent-plugin-cloudwatch-ingest/blob/master/fluent-plugin-cloudwatch-ingest.gemspec#L36

**Comment by sampointer** [comment]
I've moved onto the plugin above as this plugin doesn't seem to get much pull-request love. I therefore don't have the means to test my PR. I'm sure if you submit a PR it'll be fine.

**Comment by orasik** [comment]
Fair enough. Thanks a lot for confirming the bug. I will submit a PR in case someone faced the same error.

**Comment by liche60** [comment]
Hi, since I need to use v3 to work with other plugins, there's just two changes that need to be done, 1. install the aws-sdk-cloudwatchlogs gem and 2. adding a require aws-sdk-cloudwatchlogs to the out_cloudwatch_logs.rb, is this possible?

**Comment by mwpeterson** [comment]
Thanks for the tip, @liche60 !
I've submitted a PR if @ryotarai wants to move to v3.

**Comment by koooge** [comment]
fyi) I got the same error by `fluent-gem install fluent-plugin-s3`
