### ISSUE TITLE
SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by dieend** [ryotarai/fluent-plugin-cloudwatch-logs#9]
```
2014-12-19 05:09:55 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2014-12-19 05:13:41 +0000 error_class="Seahorse::Client::NetworkingError" error="SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed" plugin_id="object:3fb2eaa89760"
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:920:in `connect'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:101:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:920:in `connect'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:858:in `start'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/net_http/handler.rb:75:in `session'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/net_http/handler.rb:51:in `transmit'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/net_http/handler.rb:25:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/content_length.rb:12:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/request_signer.rb:73:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/rpc_body_handler.rb:9:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/rpc_headers_handler.rb:10:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/restful_bindings.rb:13:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/endpoint.rb:35:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/param_validation.rb:22:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/request.rb:70:in `send_request'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.16/lib/seahorse/client/base.rb:215:in `block (2 levels) in define_operation_methods'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:152:in `log_group_exists?'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:48:in `block in write'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `<<'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `each'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `each'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.0.7/lib/fluent/plugin/out_cloudwatch_logs.rb:45:in `write'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/buffer.rb:300:in `write_chunk'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/buffer.rb:280:in `pop'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/output.rb:311:in `try_flush'
  2014-12-19 05:09:55 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.57/lib/fluent/output.rb:132:in `run'
```

What is the reason for this error?

My configuration

```
<match test.cloudwatch_logs.out>
  type cloudwatch_logs
  aws_key_id VALID_KEY
  aws_sec_key VALID_SECRET_KEY
  region ap-southeast-1
  log_stream_name fluent-plugin-cloudwatch-example
  sequence_token_file /tmp/fluent-plugin-cloudwatch-example.seq
  auto_create_stream true
  use_tag_as_group true
</match>
```

**Comment by romanr** [comment]
This makes this plugin totally broken. Are there any workarounds? Or nobody can use this plugin at all?

**Comment by ryotarai** [comment]
If you still have a problem, please send a pull request
